import argparse
import os
import re

import numpy as np
import pandas as pd


VOTE_CLS_COLS = [
    "vote_cls_mean_prob",
    "vote_cls_std_prob",
    "vote_cls_positive_votes",
    "vote_cls_pred",
]
VOTE_REG_COLS = [
    "vote_barrier_mean",
    "vote_barrier_std",
]


def model_col_key(name: str):
    match = re.match(r"model(\d+)_(cls_prob|barrier)$", name)
    if match:
        return int(match.group(1))
    return name


def discover_model_columns(input_path: str, expected_models: int):
    header = pd.read_csv(input_path, nrows=0)
    columns = list(header.columns)
    cls_cols = sorted(
        [c for c in columns if re.match(r"model\d+_cls_prob$", c)],
        key=model_col_key,
    )
    reg_cols = sorted(
        [c for c in columns if re.match(r"model\d+_barrier$", c)],
        key=model_col_key,
    )

    if not cls_cols:
        raise ValueError(f"No model*_cls_prob columns found in {input_path}")
    if expected_models > 0 and len(cls_cols) != expected_models:
        raise ValueError(
            f"Expected {expected_models} model*_cls_prob columns, "
            f"found {len(cls_cols)}: {cls_cols}"
        )
    return columns, cls_cols, reg_cols


def output_columns(input_columns, has_reg_cols: bool):
    cols = list(input_columns)
    for col in VOTE_CLS_COLS:
        if col not in cols:
            cols.append(col)
    if has_reg_cols:
        for col in VOTE_REG_COLS:
            if col not in cols:
                cols.append(col)
    return cols


def main():
    parser = argparse.ArgumentParser("Stream-filter positive rows from vote inference CSV")
    parser.add_argument("--input", required=True, help="CSV generated by vote_infer_unlabeled.py")
    parser.add_argument("--output", required=True, help="Filtered output CSV")
    parser.add_argument("--cls_threshold", type=float, default=0.5)
    parser.add_argument(
        "--comparison",
        choices=["gt", "ge"],
        default="gt",
        help="gt: mean_prob > threshold; ge: mean_prob >= threshold",
    )
    parser.add_argument("--expected_models", type=int, default=8)
    parser.add_argument("--chunksize", type=int, default=100000)
    args = parser.parse_args()

    if args.chunksize < 1:
        raise ValueError("--chunksize must be >= 1")

    input_columns, cls_cols, reg_cols = discover_model_columns(args.input, args.expected_models)
    out_columns = output_columns(input_columns, has_reg_cols=bool(reg_cols))

    dtype = {c: "float32" for c in cls_cols + reg_cols}
    out_dir = os.path.dirname(args.output)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    tmp_output = f"{args.output}.tmp"
    if os.path.exists(tmp_output):
        os.remove(tmp_output)

    total_rows = 0
    selected_rows = 0
    wrote_header = False

    reader = pd.read_csv(args.input, chunksize=args.chunksize, dtype=dtype)
    for chunk_idx, chunk in enumerate(reader, start=1):
        cls_probs = chunk[cls_cols].to_numpy(dtype=np.float32, copy=False)
        mean_prob = np.nanmean(cls_probs, axis=1)
        std_prob = np.nanstd(cls_probs, axis=1)
        positive_votes = np.sum(cls_probs >= args.cls_threshold, axis=1)

        if args.comparison == "gt":
            pred = mean_prob > args.cls_threshold
        else:
            pred = mean_prob >= args.cls_threshold

        chunk["vote_cls_mean_prob"] = mean_prob
        chunk["vote_cls_std_prob"] = std_prob
        chunk["vote_cls_positive_votes"] = positive_votes.astype(np.int16, copy=False)
        chunk["vote_cls_pred"] = pred.astype(np.int8, copy=False)

        if reg_cols:
            reg_preds = chunk[reg_cols].to_numpy(dtype=np.float32, copy=False)
            chunk["vote_barrier_mean"] = np.nanmean(reg_preds, axis=1)
            chunk["vote_barrier_std"] = np.nanstd(reg_preds, axis=1)

        selected = chunk.loc[pred].reindex(columns=out_columns)
        if not selected.empty:
            selected.to_csv(
                tmp_output,
                mode="a",
                header=not wrote_header,
                index=False,
            )
            wrote_header = True

        total_rows += len(chunk)
        selected_rows += int(np.sum(pred))
        print(
            f"[INFO] chunk={chunk_idx}, rows={len(chunk)}, "
            f"selected={int(np.sum(pred))}, total_selected={selected_rows}",
            flush=True,
        )

    if not wrote_header:
        pd.DataFrame(columns=out_columns).to_csv(tmp_output, index=False)

    os.replace(tmp_output, args.output)
    print(
        "[INFO] Filter summary: "
        f"input={args.input}, output={args.output}, "
        f"comparison=mean_prob {args.comparison} {args.cls_threshold}, "
        f"models={len(cls_cols)}, total={total_rows}, selected={selected_rows}",
        flush=True,
    )


if __name__ == "__main__":
    main()
